---
- name: 'web'
  box: 'centos/8'
  ram: 4096
  cpus: 3
  ip: 10.0.0.5

  # Optional
  network_ports:
    - guest: 32080
      host: 8080
  disks:
    - disk:
        options:
          :size: '1G'
  nfs_folders:
    - src: 'src/web'
      dest: '/app'
  ansible:
    - playbook_name: 'ansible/common.yml'
      limit: 'web-nodes'
      groups:
        :web-nodes: ['web']

    - playbook_name: 'ansible/microk8s.yml'
      limit: 'web-nodes'
      groups:
        :web-nodes: ['web']

    - playbook_name: 'ansible/web-app.yml'
      limit: 'web-nodes'
      groups:
        :web-nodes: ['web']
