---
apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT}
spec:
  type: LoadBalancer
  selector:
    app: ${DEPLOYMENT}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32080
